name: 'Hello World'
description: 'print a hello world msg'

inputs:
  msg:
    description: "msg"

runs:
  using: 'composite'
  steps:

    - name: print_msg
      shell: bash
      env:
        MSG: "${{ msg }}"
      run: echo "$MSG"
