name: "Hello World Action"
description: "A simple action that prints a message"
inputs:
  msg:
    description: "Message to print"
    required: true
    default: "default"
runs:
  using: "composite"
  steps:
    - name: print_msg
      shell: bash
      env:
        MSG: "${{ inputs.msg }}"
      run: echo "your message: $MSG"
